### ISSUE TITLE
Release new version with recent changes

### ISSUE THREAD

**Issue by schneiderderek** [seuros/capistrano-newrelic#10]
Thanks for merging my PR (https://github.com/seuros/capistrano-newrelic/pull/9), however you didn't release a new version of the gem after you merged. Would you guys mind releasing a new version of the gem?

**Comment by sampriddy** [comment]
A new version would be greatly appreciated. I'm waiting for the fix for the hanging deploys, as well, and would love to not need to point to a specific commit to pull it in.

**Comment by schneiderderek** [comment]
@bkayser or @seuros Would one of you mind building a new release of the gem that include the most recent changes on master?

**Comment by seuros** [comment]
sure thing.

**Comment by seuros** [comment]
@schneiderderek : version 0.10.0 pushed.

**Comment by schneiderderek** [comment]
@seuros Thank you!
